# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello World CLI"
  homepage "https://github.com/go-cli-tool-workshop-2022/hello"
  version "0.1.0-dev-2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-2/hello_v0.1.0-dev-2_darwin_arm64.tar.gz"
      sha256 "13cc6f76fc4cd031ef609bb86c022493bd0d8ea44709821d8aa8b4b48e5a9bea"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-2/hello_v0.1.0-dev-2_darwin_amd64.tar.gz"
      sha256 "3285bc70209b8bbd42f7b855c78048b3eefc15155564829245e5a229cdaac8c8"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-2/hello_v0.1.0-dev-2_linux_arm64.tar.gz"
      sha256 "254f1f2539f084ab77a688c78026f4385284c42342ed243e1b6a799320a5407a"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-2/hello_v0.1.0-dev-2_linux_amd64.tar.gz"
      sha256 "aa8b40cbc6f1f37fbca5e64fbef6eae7c058f0f80adaac5a23b408cce66ca2e2"

      def install
        bin.install "hello"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/go-cli-tool-workshop-2022/hello
  EOS
  end

  test do
    system "#{bin}/hello version"
  end
end
