# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "Hello World CLI"
  homepage "https://github.com/go-cli-tool-workshop-2022/hello"
  version "0.1.0-dev-1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-1/hello_v0.1.0-dev-1_darwin_arm64.tar.gz"
      sha256 "4feb362590f0f5725a8302bdc8564f16b5325764703dd789a2149af83783d8e6"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-1/hello_v0.1.0-dev-1_darwin_amd64.tar.gz"
      sha256 "4a9ba685543f99f61403bbcb45232d4654c1d5923ce27bc427f1d71efdf0bcd0"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-1/hello_v0.1.0-dev-1_linux_arm64.tar.gz"
      sha256 "ada823b3609aa3072227853658941af9f907849c4fb5521972e9014e313130af"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-cli-tool-workshop-2022/hello/releases/download/v0.1.0-dev-1/hello_v0.1.0-dev-1_linux_amd64.tar.gz"
      sha256 "685bf17dd32732e17447ac2a527f8bcd263c5ac08424ec231d7ab49eb00d80b0"

      def install
        bin.install "hello"
      end
    end
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/go-cli-tool-workshop-2022/hello
  EOS
  end

  test do
    system "#{bin}/hello version"
  end
end
